[profile.default]
src = "../"
out = "out"
libs = ["node_modules"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

# SMTChecker configuration for formal verification
model_checker_engine = "chc"
model_checker_targets = ["all"]
model_checker_timeout = 100000

# Halmos symbolic testing
[profile.halmos]
src = "../"
test = "test/symbolic"
script = "script"
solc = "0.8.20"

# Echidna fuzzing
[profile.echidna]
sender = ["0x10000", "0x20000", "0x30000"]
deployer = "0x30000"
